sub Catch(exceptionByRef as integer)
	exceptionByRef = IOresult
end sub
